{
    "services": {
        "devcontainer": {
            "command": "sleep infinity",
            "image": "public.ecr.aws/acilearning/haskell:9.8.1",
            "init": true,
            "volumes": [
                "..:/workspaces/advent-of-code-2023"
            ],
            "working_dir": "/workspaces/advent-of-code-2023"
        }
    }
}
